source 'https://rubygems.org'

ruby '3.1.0'

gem 'sinatra', '~> 3.0'
gem 'puma', '~> 6.0'
gem 'json', '~> 2.6'
gem 'dotenv', '~> 2.8'

group :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
end

group :development, :test do
  gem 'rerun', '~> 0.14'
end